# This is a basic workflow to help you get started with Actions

name: Node.js CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    # disabled for now
    # branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    environment: SSH Deploy
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/githubdeploy/airline-ticket-agency-course-project
          git pull origin master
          git status
          docker stop air-app
          docker rm air-app
          docker rmi -f air-app
          docker build -t air-app .
          docker run -d -p 3000:3000 --name air-app air-app

# TODO: attempt to reduce ram required to build image https://github.com/vercel/next.js/discussions/19198
# TODO: fix iron session not working in production