name: Build and Deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/zxcvve/air_app:latest

  deploy:
    needs: docker
    environment: SSH Deploy
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            docker stop air_app
            docker rm air_app
            docker rmi -f ghcr.io/zxcvve/air_app
            docker pull ghcr.io/zxcvve/air_app:latest
            docker run -e DB_HOST=${{secrets.DB_HOST}} \
            -e DB_PASSWORD=${{secrets.DB_PASSWORD}} \
            -e DB_USER=${{secrets.DB_USER}} \
            -e DB_NAME=${{secrets.DB_NAME}} \
            -e SESSION_PASSWORD=${{secrets.SESSION_PASSWORD}} \
            -e URL=${{secrets.URL}} \
            -d -p 3000:3000 --name air_app ghcr.io/zxcvve/air_app:latest
